#!/usr/bin/env python

"""

Generated by Logomancy Prometheus

Copyright © 2023 Ian McFarland and Logomancy
All Rights Reserved

	Filename: hello.py
	Language: Python
	Author: Prometheus
		* Base Prompt: Create a script that says Hi

THIS SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
It wasn't even made by humans, though the computers gave it their best shot.
Use at your own risk, and make sure it does what you want it to.

Learn more at https://prometheus.logomancy.co/


"""
print("Hi")
